// @ts-check
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Writes dist/sw.js after the build: precaches every page and asset so the
 * app keeps working on unreliable exhibition Wi-Fi. Firebase traffic is never cached.
 * @returns {import('astro').AstroIntegration}
 */
export default function offline() {
  return {
    name: 'mindmate-offline',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const root = fileURLToPath(dir);
        /** @type {string[]} */
        const files = [];
        /** @param {string} d */
        const walk = async (d) => {
          for (const entry of await readdir(d, { withFileTypes: true })) {
            const p = join(d, entry.name);
            if (entry.isDirectory()) await walk(p);
            else files.push(p);
          }
        };
        await walk(root);

        const hash = createHash('sha256');
        const urls = [];
        for (const f of files.sort()) {
          const rel = relative(root, f).split(sep).join('/');
          if (rel === 'sw.js' || rel.endsWith('.map')) continue;
          hash.update(rel).update(await readFile(f));
          if (rel.endsWith('index.html')) urls.push('/' + rel.replace(/index\.html$/, '').replace(/\/$/, ''));
          else if (rel.endsWith('.html')) urls.push('/' + rel.replace(/\.html$/, ''));
          else urls.push('/' + rel);
        }
        const version = hash.digest('hex').slice(0, 12);
        const sw = `// Generated by integrations/offline.mjs: do not edit.
const CACHE = 'mindmate-${version}';
const PRECACHE = ${JSON.stringify(urls.map((u) => (u === '' ? '/' : u)))};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) return;
  // Pages: network first so updates show up, cache when offline.
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(event.request, copy));
          return res;
        })
        .catch(() => caches.match(event.request, { ignoreSearch: true }).then((r) => r || caches.match('/'))),
    );
    return;
  }
  // Hashed assets: cache first.
  event.respondWith(caches.match(event.request).then((r) => r || fetch(event.request)));
});
`;
        await writeFile(join(root, 'sw.js'), sw);
        logger.info(`sw.js written: ${urls.length} files precached (v${version})`);
      },
    },
  };
}
